CREATE DATABASE QuanLy_HS_GV_THPT
USE QuanLy_HS_GV_THPT
GO
CREATE TABLE HOCSINH
(
	MaHS VARCHAR(10) PRIMARY KEY,
	HoTenHS NVARCHAR(50),
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam',N'Nữ')),
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	SDT VARCHAR(10) , -- sdt phụ huynh 
	MaLT VARCHAR(10), --Lớp Trưởng
	MaBT VARCHAR(10), --Bí Thư
	HanhKiem VARCHAR(10),
	NienKhoa VARCHAR(10),
	DanToc NVARCHAR(20),
	MaLop VARCHAR(10) REFERENCES dbo.LOP(MaLop)
);

CREATE TABLE DIEM
(
	DiemSo FLOAT ,
	LoaiDiem NVARCHAR(50) ,
	NamHoc VARCHAR(20) ,
	HocKy VARCHAR(10) CHECK (HocKy IN (N'Học Kỳ I' , N'Học Kỳ II')) ,
	MaHS VARCHAR(10) REFERENCES dbo.HOCSINH(MaHS) ,
	MaMH VARCHAR(10) REFERENCES dbo.MONHOC(MaMH) 
);

CREATE TABLE MONHOC
(
	MaMH VARCHAR(10) PRIMARY KEY,
	TenMH NVARCHAR(30) ,
	KhoiMH VARCHAR(5) 
);

CREATE TABLE GIAOVIEN
(
	MaGV VARCHAR(10) PRIMARY KEY ,
	HoTenGV NVARCHAR(50) ,
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam',N'Nữ')),
	NgaySinh DATE ,
	DiaChi NVARCHAR(100) , 
	SDT VARCHAR(10) ,
	MaHT VARCHAR(10) ,
	MaMH VARCHAR(10) REFERENCES dbo.MONHOC(MaMH)
);

CREATE TABLE LOP
(
	MaLop VARCHAR(10) PRIMARY KEY,
	TenLop NVARCHAR(10) ,
	MaGV VARCHAR(10) REFERENCES dbo.GIAOVIEN(MaGV) ,
	MaKhoi VARCHAR(10) REFERENCES dbo.KHOILOP(MaKhoi) 

);

CREATE TABLE KHOILOP
(
	MaKhoi VARCHAR(10) PRIMARY KEY,
	TenKhoi NVARCHAR(10) 
);

ALTER TABLE dbo.GIAOVIEN ADD Luong INT 