create database QLKHO
GO
USE QLKHO
GO
create table DONVI
(
	ID int identity(1,1) primary key,
	TEN nvarchar(max),

)
GO
create table NHACC
(
	ID int identity(1,1) primary key,
	TENNCC nvarchar(max),
	DIACHI nvarchar(max),
	PHONE nvarchar(20),
	EMAIL NVARCHAR(200),
	NGAYHT DATETIME,
)
GO
create table KHACHHANG
(
	ID int identity(1,1) primary key,
	TENNCC nvarchar(max),
	DIACHI nvarchar(max),
	PHONE nvarchar(20),
	EMAIL NVARCHAR(200),
	NGAYHT DATETIME,
)
GO
create table HANGHOA
(
	ID NVARCHAR(128) PRIMARY KEY,
	TENHH NVARCHAR(MAX),
	IDDV INT NOT NULL,
	IDNCC INT NOT NULL,

	FOREIGN KEY (IDDV) REFERENCES DONVI(ID),
	FOREIGN KEY (IDNCC) REFERENCES NHACC(ID)


)
GO
CREATE TABLE USEROLE
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	TEN NVARCHAR(MAX)
)
GO
INSERT INTO USEROLE(TEN) VALUES(N'ADMIN')
GO
INSERT INTO USEROLE(TEN) VALUES(N'NHÂN VIÊN')
GO

create TABLE USERS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENHT NVARCHAR(MAX),
	USERNAME NVARCHAR(100),
	PASSWORD NVARCHAR(MAX),
	IDROLE INT NOT NULL,
	FOREIGN KEY (IDROLE) REFERENCES USEROLE(ID),
)
GO
INSERT INTO USERS(TENHT,USERNAME,PASSWORD, IDROLE) VALUES (N'HUYDZ',N'ADMIN',N'PASSWORD',1)
INSERT INTO USERS(TENHT,USERNAME,PASSWORD, IDROLE) VALUES (N'HUYDZY',N'STAFF',N'STAFF',2)
CREATE TABLE PHIEUNHAP
(
	ID NVARCHAR(128) PRIMARY KEY,
	NGAYNHAP DATETIME,
)
GO
CREATE TABLE TTPHIEUNHAP
(
	ID NVARCHAR(128) PRIMARY KEY,
	IDHH NVARCHAR(128) NOT NULL,
	IDPHIEUNHAP NVARCHAR(128) NOT NULL,
	COUNT INT,
	GIANHAP FLOAT DEFAULT 0,
	GIAXUAT FLOAT DEFAULT 0,
	FOREIGN KEY (IDHH) REFERENCES HANGHOA(ID),
	FOREIGN KEY (IDPHIEUNHAP) REFERENCES PHIEUNHAP(ID),
	STATUS NVARCHAR(MAX)
)
GO
CREATE TABLE PHIEUXUAT
(
	ID NVARCHAR(128) PRIMARY KEY,
	NGAYXUAT DATETIME,
)
GO
CREATE TABLE TTPHIEUXUAT
(
	ID NVARCHAR(128) PRIMARY KEY,
	IDHH NVARCHAR(128) NOT NULL,
	IDTTPHIEUNHAP NVARCHAR(128) NOT NULL,
	IDKH INT NOT NULL,
	COUNT INT,
	
	FOREIGN KEY (IDHH) REFERENCES HANGHOA(ID),
	FOREIGN KEY (IDTTPHIEUNHAP) REFERENCES TTPHIEUXUAT(ID),
	FOREIGN KEY (IDKH) REFERENCES KHACHHANG(ID),

)
GO
